=== ehs2803/College/웹정보프레임워크/week6 practice assignment/ex4-5/audioCatalog.xsd
<?xml version="1.0"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
          targetNamespace="http://www.ehs.com/audio" 
          xmlns:target="http://www.ehs.com/audio" 
          elementFormDefault="qualified"> 

     <group name="AlbumGroup">
          <sequence>
               <element name="Title" type="string"/>
               <element name="Artist" type="string"/>
               <element name="Genre" type="string"/>
               <element name="Released-data" type="string"/>
               <element name="Song" type="string" maxOccurs="unbounded" />
          </sequence>
     </group>

     <element name="AudioCatalog">
          <complexType>
               <choice maxOccurs="unbounded">
                    <element name="Cd">
                         <complexType>
                              <group ref="target:AlbumGroup" />
                         </complexType>
                    </element>
                    <element name="Record">
                         <complexType>
                              <group ref="target:AlbumGroup" />
                         </complexType>
                    </element>
                    <element name="Mp3">
                         <complexType>
                              <group ref="target:AlbumGroup" />
                         </complexType>
                    </element>
               </choice>
          </complexType>
     </element>
</schema>

=== ehs2803/College/웹정보프레임워크/week6 practice assignment/ex4-5/audioCatalog.xml
<?xml version="1.0"?>
<AudioCatalog xmlns="http://www.ehs.com/audio" 
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
          xsi:schemaLocation="http://www.ehs.com/audio audioCatalog.xsd" > 
     <Cd>
          <Title> BTS 1집 </Title>
          <Artist> BST </Artist>
          <Genre> dance </Genre>
          <Released-data> 2017 </Released-data>
          <Song> 1번곡 </Song>
          <Song> 2번곡 </Song>
          <Song> 3번곡 </Song>
     </Cd>
     <Cd>
          <Title> BTS 2집 </Title>
          <Artist> BST </Artist>
          <Genre> dance </Genre>
          <Released-data> 2020 </Released-data>
          <Song> 1번곡 </Song>
          <Song> 2번곡 </Song>
          <Song> 3번곡 </Song>
     </Cd>
     <Record>
          <Title> BTS 3집 </Title>
          <Artist> BST </Artist>
          <Genre> dance </Genre>
          <Released-data> 2021 </Released-data>
          <Song> 1번곡 </Song>
          <Song> 2번곡 </Song>
          <Song> 3번곡 </Song>
     </Record>
     <Mp3>
          <Title> BTS 4집 </Title>
          <Artist> BST </Artist>
          <Genre> dance </Genre>
          <Released-data> 2021 </Released-data>
          <Song> 1번곡 </Song>
          <Song> 2번곡 </Song>
          <Song> 3번곡 </Song>
     </Mp3>
</AudioCatalog>
